quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/loja-quarkus-java
quarkus.datasource.username=postgres
quarkus.datasource.password=123456

quarkus.hibernate-orm.database.generation=update
